[feature/loginService > develop][#3]
AppDev-FootPrint/FootPrint-backend pull request #5
Opened 2022-05-19 11:50 UTC by ShinDongHun1

구현한 기능

- Spring Security 추가
- 회원가입 기능 구현
- Json으로 로그인하는 필터 구현 
- JWT를 사용하여 인증하는 필터 구현

TODO 

- JWT에 member의 pk(Id)만 가지도 있도록 하여, 이대로 배포할 경우 보안상 문제가 생길 수 있음 
    - 관련 method : JwtService의 createAccessToken
  
- SecurituConfig 의 .antMatchers("/login", "/signUp").permitAll()
    - url을 이렇게 관리할지, 필드로 따로 빼서 관리할지 고민

- JwtAuthenticationFilter가 Filter를 구현하는 경우 두번 작동하는 문제
    - OncePerRequestFilter를 상속받도록 하여 고쳤으나, Filter를 구현할 경우 왜 두번 작동하는지 모르겠음

close #3

2022-05-19 12:55 UTC, ProtoSeo requested changes
확인해주시면 감사하겠습니다!

2022-05-19 12:55 UTC, ProtoSeo commented on src/main/java/com/footprint/member/controller/SignUpRequest.java
> +public record SignUpRequest (String username, String password, String nickName) {
저희가 `Member` 도메인에서 별명을 `nickname`으로 사용하고 있기도 하고, nickname 자체가 하나의 명사여서 nickName보다는 nickname으로 사용하는 것이 어떨까요?

2022-05-19 12:55 UTC, ProtoSeo commented on src/test/java/com/footprint/auth/AuthTest.java
> +		authMap.put("password", "1");
잘못된 비밀번호로 1을 주는 것보다 명확하게 `"wrong-password"` 이렇게 주는 것은 어떨까요?

2022-05-19 12:59 UTC, ProtoSeo commented on src/main/java/com/footprint/config/SecurityConfig.java
> +			.antMatchers("/login", "/signUp").permitAll()//TODO 따로 빼서 관리하는 것이 나을지, 아니면 이대로 사용할지
따로 빼서 관리한다는 것이 어떤 방식으로 하는 건지 궁금해요!

2022-05-19 13:01 UTC, ProtoSeo commented on src/main/java/com/footprint/member/exception/MemberExceptionType.java
> +	private final int errorCode;
저 errorCode에 대해서 생각해봤는데 `String` 으로 에러코드를 주면 어떨까요? Member 관련 에러면 `M101`, `M102`.. 댓글 관련이면 `C101`, `C102`.. 이런 식으로,, 이건 나중에 더 이야기 해보면 좋을 것 같아요! 저는 일단은 HttpStatus의 value값으로 구현했습니다.

2022-05-19 13:10 UTC, ProtoSeo commented on src/main/java/com/footprint/member/exception/MemberExceptionType.java
> +	private final int errorCode;
errorCode관련해서 생각해봤는데, String으로 관리하는 것은 어떨까요? Member 관련 예외면, `M101`, `M102` ... 그리고 댓글 관련이면 `C101`, `C102`... 이런식으로 말이죠! 이건 나중에 더 얘기 나눠보면 좋을 것 같습니다! 저는 지금은 HttpStatus value값 가져와서 예외처리 하도록 구현했습니당

2022-05-19 14:05 UTC, shin-mallang commented on src/main/java/com/footprint/member/controller/SignUpRequest.java
> +public record SignUpRequest (String username, String password, String nickName) {
Camel case가 습관이 되어서 nickName으로 적은 것 같습니다. 수정하겠습니다.

2022-05-19 14:08 UTC, ShinDongHun1 commented on src/test/java/com/footprint/auth/AuthTest.java
> +		authMap.put("password", "1");
`static final String WRONG_STRING = "wrong-password"` 은 어떨까요?

2022-05-19 14:10 UTC, ShinDongHun1 commented on src/main/java/com/footprint/config/SecurityConfig.java
> +			.antMatchers("/login", "/signUp").permitAll()//TODO 따로 빼서 관리하는 것이 나을지, 아니면 이대로 사용할지
변수로 추출해서 `List<String> permitAllUrls =  Arrays.asList("/login", "/signUp')` 식으로 관리하는것을 생각해보았습니다.

2022-05-19 14:13 UTC, ProtoSeo commented on src/test/java/com/footprint/auth/AuthTest.java
> +		authMap.put("password", "1");
좋습니당!

2022-05-19 14:13 UTC, ShinDongHun1 commented on src/main/java/com/footprint/member/exception/MemberExceptionType.java
> +	private final int errorCode;
좋은 생각인 것 같습니다.
수정은 지금 바로 할까요?

2022-05-19 14:18 UTC, ProtoSeo commented on src/main/java/com/footprint/member/exception/MemberExceptionType.java
> +	private final int errorCode;
아뇨! 나중에 프론트랑 errorCode 관련된 이야기 할 때? 그 때 같이 수정하면 될것 같아요!

2022-05-19 14:19 UTC, ProtoSeo commented on src/main/java/com/footprint/config/SecurityConfig.java
> +			.antMatchers("/login", "/signUp").permitAll()//TODO 따로 빼서 관리하는 것이 나을지, 아니면 이대로 사용할지
아항! 이건 뭐가 더 좋은 방법일지 좀 더 생각해보면 좋을 것 같아요! 지금은 이렇게 해도 괜찮을 것 같습니다~

2022-05-19 18:35 UTC, ShinDongHun1 commented
수정 완료했습니다! 
봐주시면 감사하겠습니다 :D

2022-05-20 02:18 UTC, ProtoSeo approved these changes

2022-05-20 02:20 UTC, merged