[feature/main-travel > develop][#4] MainTravel 기본 기능 구현
AppDev-FootPrint/FootPrint-backend pull request #6
Opened 2022-05-22 04:49 UTC by ProtoSeo

구현한 기능
- MainTravel Repository, Service, Controller 구현
  - MainTravel 단일 조회 기능
  - MainTravel 저장 기능
  - MainTravel 수정 기능
  - MainTravel 삭제 기능
 - 관련 단위 테스트 구현
TODO
- Member 작성자로 연결 하도록 구현
- Detail Travel 구현 후 `detailTravels` 에 추가하도록 구현
- Heart 구현 후 `hearts`에 이를 저장하도록 구현
- Scrap 구현 후 `scraps`에 이를 저장하도록 구현
- 이 후 테스트 수정

2022-05-22 05:53 UTC, ShinDongHun1 requested changes
확인해주시면 감사하겠습니다 :D

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +		return ResponseEntity.created(location).body(saveMainTravelId);
Long을 반환하는 이유가 따로 있으신가요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +		return ResponseEntity.noContent().build();
Delete 요청이 성공한거라 noContent 대신 ok가 낫다고 생각하는데 어떻게 생각하시나요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +	@GetMapping("/main-travels/{mainTravelId}")
mainTravelId 대신 id로 적는 것은 어떻게 생각하시나요?
저는 MainTravelController이기 때문에 mainTravel이 굳이 붙지 않아도 명확하다 생각합니다

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +	@PatchMapping("/main-travels/{mainTravelId}")
Put이 아닌 Patch를 사용하신 이유가 있으신가요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/controller/dto/MainTravelRequest.java
> +public record MainTravelRequest(
MainTravel을 생성할때 사용하는 Dto와 수정할때 사용하는 Dto를 각각 만들어서 관리하는건 어떻게 생각하시나요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/domain/MainTravel.java
> +	public void update(String title, LocalDate startDate, LocalDate endDate, Boolean isVisible, Boolean isCompleted) {
update 처리를 하는 방식에 대해 논의해봐야 할 것 같습니다

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/service/MainTravelService.java
> +	Long saveMainTravel(MainTravelSaveDto saveDto);
마찬가지로 Long 을 반환하는 이유가 있을까요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/service/MainTravelServiceImpl.java
> +		MainTravel save = mainTravelRepository.save(MainTravel.builder()
해당 과정을 MainTravelSaveDto에 추가하여 saveDto.toEntity() 형식으로 바꾸는 것은 어떻게 생각하시나요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/service/MainTravelServiceImpl.java
> +		MainTravel mainTravel = mainTravelRepository.findById(mainTravelId).orElseThrow();
여기서 예외처리 따로 안하신 이유가 있으신가요?

2022-05-22 05:53 UTC, ShinDongHun1 commented on src/main/java/com/footprint/maintravel/service/dto/MainTravelDto.java
> +public record MainTravelDto(
createdDate도 포함되어야 하지 않을까요?

2022-05-22 06:03 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +	@GetMapping("/main-travels/{mainTravelId}")
좋은 의견인것 같습니당 수정하겠습니다!

2022-05-22 06:15 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/service/dto/MainTravelDto.java
> +public record MainTravelDto(
ERD랑 도메인에도 없어서, 일단 도메인이랑 ERD에 추가하고 추가하도록 하겠습니당~

2022-05-22 06:16 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/service/MainTravelServiceImpl.java
> +		MainTravel save = mainTravelRepository.save(MainTravel.builder()
괜찮을것같아요~ 수정하도록 하겠습니당~

2022-05-22 06:18 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/controller/dto/MainTravelRequest.java
> +public record MainTravelRequest(
Save할 때랑 Update할 때 body 내용이 똑같을것 같아서, request dto로만 으로도 충분할 것 같아요!

2022-05-22 06:22 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +		return ResponseEntity.noContent().build();
<img width="792" alt="image" src="https://user-images.githubusercontent.com/55012742/169681712-7ed4eed2-07f8-4467-a821-09071c3d49ac.png">

[MDN 200 OK](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/200) 보고 No Content를 사용했는데, 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/55012742/169681761-478507e8-9914-44a4-b4a4-f87ea588dfae.png">

이걸 보고나서, 저희는 삭제하고 클라이언트의 페이지가 옮겨지니까 ok가 더 좋을 것같네요! 수정하도록 하겠습니당

2022-05-23 09:37 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/domain/MainTravel.java
> +	public void update(String title, LocalDate startDate, LocalDate endDate, Boolean isVisible, Boolean isCompleted) {
넹! 일단 지금은 수정하지 않고 남겨두겠습니당. 만약 update에서, dto에 들어오는 값을 null 체크하고 하나씩 저장하게 된다면, save 단계에서도 null 체크를 해야할 것 같아요!

2022-05-23 09:38 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +	@PatchMapping("/main-travels/{mainTravelId}")
여기서는 Put이 맞을것같아요! Patch는 부분부분 변경할 때 사용하는 것이네용.. 제가 put이랑 patch랑 헷갈렸습니다..ㅜ 수정하도록 하겠습니당~

2022-05-23 09:41 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/service/MainTravelServiceImpl.java
> +		MainTravel mainTravel = mainTravelRepository.findById(mainTravelId).orElseThrow();
빼놓고 구현했네용,, 추가했습니당!

2022-05-23 09:55 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/controller/MainTravelController.java
> +		return ResponseEntity.created(location).body(saveMainTravelId);
이건 클라이언트에서 저장이나 업데이트 후에 어떤 화면을 보여줄 것인가에 따라 다른것같긴한데, 제 개인적인 생각으로는 저장 후에, 저장이 완료되었다는 화면이 나온 다음에 게시글 화면으로 이동할 때, 게시글의 id가 필요하지 않을까 해서 Long을 반환하도록 하였습니당!

2022-05-23 09:56 UTC, ProtoSeo commented on src/main/java/com/footprint/maintravel/service/MainTravelService.java
> +	Long saveMainTravel(MainTravelSaveDto saveDto);
위에 참고해주세요!

2022-05-23 11:17 UTC, merged